### ISSUE TITLE
Lancement de l'application

### ISSUE THREAD

**Issue by LauraPereira** [fleebzz/lpdip.2020.projects.todos#1]
Bonjour,

J'ai une erreur de symlink lorsque je regarde les logs pour lancer l'application. J'avais trouvé un flag '--no-bin-links mais çane fonctionne pas. Je sais que j'avais déjà eu le problème mais je ne me souviens pas de comment il avait été résolu ou contourné. 
![Capture](https://user-images.githubusercontent.com/37901764/80578191-62ca0680-8a08-11ea-9e53-f2f26140375e.PNG)

Et du coup l'application ne se lance pas.
![image](https://user-images.githubusercontent.com/37901764/80578501-d4a25000-8a08-11ea-858f-fce124944d92.png)

Edit : Résolu en lançant docker en administrateur.

**Comment by fleebzz** [comment]
Bonjour Laura et désolé pour le délai de réponse je n'ai pas eu de notification de la part de Github je vais vérifier mes réglages. Heureux de voir que tu as pu résoudre ton problème en tout cas, je clos cette issue.
