### ISSUE TITLE
Lancement de l'application #2

### ISSUE THREAD

**Issue by bchwebdev** [fleebzz/lpdip.2020.projects.todos#2]
Bonjour Florian,

Je n'arrive pas à utiliser les commandes que tu as mis en ligne. Le container créé ne fonctionne pas et je n'arrive pas à l'atteindre avec l'adresse URL. Ci-dessous la réponse du terminal docker.

![image](https://user-images.githubusercontent.com/59795716/80708317-c4af6c80-8aeb-11ea-992f-6759ad6d32e3.png)

Dans l'attente de ta réponse,
Cordialement,
Benjamin

**Comment by Wfontesd** [comment]
D'après l'erreur tu n'était pas positionner au bon endroit lors de la création de ton docker ou bien il y a eu une erreur lors du git clone, si tu peux, fournis les screen de ton dossier ou => discord ^^

**Comment by bchwebdev** [comment]
Re Florian, et oui c'est ce que je me suis dis aussi mais je n'ai pas réussi à le réparer.
Du coup je suis passé sur une vm ubuntu et ça marche nickel.
Merci pour ta rapide réponse en tout cas ^^

**Comment by fleebzz** [comment]
Bonjour Benjamin et désolé pour le délai de réponse je n'ai pas eu de notification de la part de Github je vais vérifier mes réglages.
Comme tu te doutes avec cette réponse, ce n'est pas moi qui t'ai répondu il y a 11 jours mais c'était William.
Heureux de voir que tu as pu résoudre ton problème en tout cas, je clôture cette issue.
