### ISSUE TITLE
this.onResult is not a function

### ISSUE THREAD

**Issue by LauraPereira** [fleebzz/lpdip.2020.projects.todos#4]
![image](https://user-images.githubusercontent.com/37901764/81818945-f46c6480-952e-11ea-9ed9-9c4ce85ecb58.png)
Tout fonctionnait très bien ce matin. Cet après-midi à part une mise à jour Windows rien à changer.

**Comment by fleebzz** [comment]
Est-ce que ta base de données est bien lancée ? Peux-tu me faire voir la liste des containers qui tournent actuellement sur ta machine ? `docker ps`

**Comment by LauraPereira** [comment]
![image](https://user-images.githubusercontent.com/37901764/81828356-01428580-953a-11ea-916e-856c2a924423.png)
Ma base de donnée est lancé puisque le get fonctionne sur ma page.

**Comment by fleebzz** [comment]
Du coup est-ce que tu peux commit et push ton code et me dire à quel endroit précisément ton code provoque cette erreur ?

**Comment by LauraPereira** [comment]
J'ai déposé les fichiers sur ma fork. L'erreur ce produit lorsque je veux ajouter une tâche.

**Comment by fleebzz** [comment]
À la ligne 55 (et à chaque endroit où tu passes des paramètres à ta requête) tu fais ça : 
```javascript
conn.query("INSERT INTO todos(label, idList, isDone) VALUES (?,?,0);",[label], [idList], function (err, fields) {
```
Ce qui pose problème dans ce code c'est cette partie là => `[label], [idList]`

Tu passes 2 tableaux à ta fonction alors qu'elle attend un seul tableau avec 2 valeurs, donc à priori ça donnerait quelque chose comme ça :
```javascript
conn.query("INSERT INTO todos(label, idList, isDone) VALUES (?,?,0);",[label, idList], function (err, fields) {
```

Tiens moi au courant si ça fonctionne mieux et si c'est le cas modifies les autres endroits 😉

**Comment by LauraPereira** [comment]
Merci, mais maintenant c'est une autre erreur qui s'affiche ^^' 
![image](https://user-images.githubusercontent.com/37901764/81831536-c2aeca00-953d-11ea-8ac1-1d51102b04e8.png)
Je fais un test pour afficher "fields" et ça me retourne vide, je sais pas trop si c'est normal ou pas ?

**Comment by fleebzz** [comment]
Ça ce n'est plus du tout la même chose, ça veut juste dire que quand tu as créé ta table tu n'as pas mis le champ `id` en `auto increment` donc il attend que tu lui donnes une valeur. Je te laisse chercher comment modifier ta table 😄

**Comment by LauraPereira** [comment]
Merci !
